In [1]:
using JuMP
using GLPKMathProgInterface

In [2]:
function sudokusolver(board)
    m = Model(solver=GLPKSolverMIP())
    @variable(m, x[1:9, 1:9, 1:9], Bin)
    for i in 1:9, j in 1:9
        @constraint(m, sum(x[i, j, :]) == 1)
        @constraint(m, sum(x[i, :, j]) == 1)
        @constraint(m, sum(x[:, i, j]) == 1)
        for (i, j, k) in board
            @constraint(m, x[i, j, k] == 1)
        end
    end
    for i in 0:2, j in 0:2, k in 1:9
        @constraint(m, sum(x[3i .+ (1:3), 3j .+ (1:3), k]) == 1)
    end

    solution_count = 0
    sol = zeros(Int, 9, 9)
    while true
        res = solve(m)
        if res == :Optimal
            solution_count += 1
            display("Solution #$solution_count")
            xv = round.(Int, getvalue(x))
            for idx in findall(==(1), xv)
                sol[idx[1], idx[2]] = idx[3]
            end
            display(sol)
            @constraint(m, sum(xv .* x) <= 80)
        else
            display("All board solutions have been found")
            return
        end
    end
end

sudokusolver (generic function with 1 method)

In [3]:
board = [(1,1,5),(1,2,3),(1,5,7),(2,1,6),(2,4,1),(2,5,9),(2,6,5),
         (3,2,9),(3,3,8),(3,8,6),(4,1,8),(4,5,6),(4,9,3),(5,1,4),
         (5,4,8),(5,6,3),(5,9,1),(6,1,7),(6,5,2),(6,9,6),(7,2,6),
         (7,7,2),(7,8,8),(8,4,4),(8,5,1),(8,6,9)]

sudokusolver(board)

"Solution #1"

9×9 Array{Int64,2}:
 5  3  4  6  7  8  1  9  2
 6  7  2  1  9  5  3  4  8
 1  9  8  3  4  2  5  6  7
 8  5  9  7  6  1  4  2  3
 4  2  6  8  5  3  9  7  1
 7  1  3  9  2  4  8  5  6
 9  6  1  5  3  7  2  8  4
 2  8  7  4  1  9  6  3  5
 3  4  5  2  8  6  7  1  9

"Solution #2"

9×9 Array{Int64,2}:
 5  3  4  6  7  8  9  1  2
 6  7  2  1  9  5  3  4  8
 1  9  8  3  4  2  5  6  7
 8  5  9  7  6  1  4  2  3
 4  2  6  8  5  3  7  9  1
 7  1  3  9  2  4  8  5  6
 9  6  1  5  3  7  2  8  4
 2  8  7  4  1  9  6  3  5
 3  4  5  2  8  6  1  7  9

"Solution #3"

9×9 Array{Int64,2}:
 5  3  4  6  7  8  1  9  2
 6  7  2  1  9  5  3  4  8
 1  9  8  3  4  2  7  6  5
 8  5  9  7  6  1  4  2  3
 4  2  6  8  5  3  9  7  1
 7  1  3  9  2  4  8  5  6
 9  6  1  5  3  7  2  8  4
 2  8  5  4  1  9  6  3  7
 3  4  7  2  8  6  5  1  9

"All board solutions have been found"

┌ Warning: Not solved to optimality, status: Infeasible
└ @ JuMP C:\Users\bogum\.julia\packages\JuMP\PbnIJ\src\solvers.jl:212
┌ Warning: Infeasibility ray (Farkas proof) not available
└ @ JuMP C:\Users\bogum\.julia\packages\JuMP\PbnIJ\src\solvers.jl:223
